# Generated by Django 5.2.9 on 2026-01-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_views_alter_board_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
